name: Terri Rowan RMT
favicon: null
layout_spectrum: 0.6191798981744796
typography_spectrum: 0.890617704950273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#555354'
    - '#c8c6c7'
    - '#5a7e9e'
  brandStrength: 0.8639812378678471
  lightness: 0.4375
  saturation: 0.8175616406369954
  rhythmicContrast: 0.25
purpose: []
