name: Terri Rowan RMT
favicon: null
layout_spectrum: 0.6191798981744796
typography_spectrum: 0.890617704950273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8639812378678471
  lightness: 0.586168966954574
  saturation: 0.8175616406369954
  rhythmicContrast: 0.5996547630056739
purpose: []
